# Generated by Django 3.2.4 on 2021-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Product_favorites',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
