# Generated by Django 3.2.4 on 2021-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0004_alter_userprofile_product_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Product_favorites',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
