# Generated by Django 3.2.4 on 2021-06-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['publish_date']},
        ),
    ]
